apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:                   # Environment variables from ConfigMap
                name: user-config
            - secretRef:                      # Secrets from Secret
                name: user-secret
